<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Configuration\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Organisation.Domain\Organisation.Domain.csproj" />
  </ItemGroup>

</Project>
